version: 3
# https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md

paths:
  # exclude non-distributed projects from dependency scanning
  exclude:
    - akka-http-bench-jmh
    - akka-http-compatibility-tests
    - akka-http-scalafix
