name: Dependency License Scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # At 00:00 on saturdays

permissions:
  contents: read

jobs:
  fossa:
    name: Fossa
    runs-on: Akka-Default
    if: github.repository == 'akka/akka-http'
    steps:
      - name: Checkout Global Scripts
        uses: actions/checkout@v6
        with:
          repository: akka/github-actions-scripts
          path: scripts
          fetch-depth: 0

      - name: Setup global resolver
        run: |
          chmod +x ./scripts/setup_global_resolver.sh
          ./scripts/setup_global_resolver.sh

      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK temurin:1.17
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.17

      - name: "fossa analyze"
        # https://github.com/fossas/fossa-action/releases/tag/v1.3.1
        uses: fossas/fossa-action@v1.8.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}

      - name: "fossa test"
        # https://github.com/fossas/fossa-action/releases/tag/v1.3.1
        uses: fossas/fossa-action@v1.8.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          run-tests: true
