name: Link Validator

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 1'

permissions:
  contents: read

jobs:
  validate-links:
    runs-on: Akka-Default
    if: github.event.repository.fork == false
    steps:
      - name: Checkout Global Scripts
        uses: actions/checkout@v6
        with:
          repository: akka/github-actions-scripts
          path: scripts
          fetch-depth: 0

      - name: Setup global resolver
        run: |
          chmod +x ./scripts/setup_global_resolver.sh
          ./scripts/setup_global_resolver.sh

      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with: # https://github.com/olafurpg/setup-scala#faster-checkout-of-big-repos
          fetch-depth: 100
          fetch-tags: true

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK 11
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.11
          apps: cs

      - name: sbt site
        run: sbt docs/paradox

      - name: Run Link Validator
        run: cs launch net.runne::site-link-validator:0.2.5 -- scripts/link-validator.conf
