name: Native Image Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  native-image-tests:
    name: Run Native Image Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Set up JDK 11
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.11

      - name: Gather version
        # some cleanup of the sbt output to get the version sbt will use when publishing below
        run: |-
          sbt "akka-http-core/version" --batch --no-colors | tail -n 1 | cut -f 2 -d ' ' | tr -d '\n' > ~/.version
          echo [$(cat ~/.version)]
          # useful for debugging: hexdump -c ~/.version

      - name: Publish artifacts locally
        run: |-
          sbt "publishLocal"

      - name: Akka HTTP native image test app build
        run: |-
          cd native-image-tests/
          sbt nativeImage -Dakka.http.version=`cat ~/.version`
          # run the binary
          target/native-image/native-image-tests

      - name: Email on failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@6063705cefe50cb915fc53bb06d4049cae2953b2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Failed: ${{ github.workflow }} / ${{ github.job }}"
          to: ${{secrets.MAIL_SEND_TO}}
          from: Akka CI
          body: |
            Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{github.repository}} failed!
            https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
