name: 'Publish Test Reports'
on:
  workflow_run:
    workflows: ['Validate and test']                     # runs after CI workflow
    types:
      - completed
jobs:
  publish-test-results:
    name: "Publish details with dorny-test-reporter"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SCALA_VERSION: [ 2.12, 2.13 ]
        JABBA_JDK: [ 1.8, 1.11 ]
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results-${{ matrix.JABBA_JDK }}-${{ matrix.SCALA_VERSION }}
          name: Test Results Details / Scala ${{ matrix.SCALA_VERSION }} on JDK ${{ matrix.JABBA_JDK }}
          fail-on-error: 'false'
          path: '**/target/test-reports/*.xml'
          reporter: java-junit
